// Mocks generated by Mockito 5.0.17 from annotations
// in cat_news/test/data/chat_view_model_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:cat_news/common/data/datasources/datasource_contract.dart'
    as _i2;
import 'package:cat_news/common/entities/entities.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [IDatasource].
///
/// See the documentation for Mockito's code generation for more information.
class MockIDatasource extends _i1.Mock implements _i2.IDatasource {
  MockIDatasource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> addChat(_i4.ChatEntity? chat) =>
      (super.noSuchMethod(Invocation.method(#addChat, [chat]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<void> addMessage(_i4.LocalMessageEntity? message) =>
      (super.noSuchMethod(Invocation.method(#addMessage, [message]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<_i4.ChatEntity?> findChat(String? chatId) =>
      (super.noSuchMethod(Invocation.method(#findChat, [chatId]),
              returnValue: Future<_i4.ChatEntity?>.value())
          as _i3.Future<_i4.ChatEntity?>);
  @override
  _i3.Future<List<_i4.ChatEntity>> findAllChats() => (super.noSuchMethod(
          Invocation.method(#findAllChats, []),
          returnValue: Future<List<_i4.ChatEntity>>.value(<_i4.ChatEntity>[]))
      as _i3.Future<List<_i4.ChatEntity>>);
  @override
  _i3.Future<void> updateMessage(_i4.LocalMessageEntity? message) =>
      (super.noSuchMethod(Invocation.method(#updateMessage, [message]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
  @override
  _i3.Future<List<_i4.LocalMessageEntity>> findMessages(String? chatId) =>
      (super.noSuchMethod(Invocation.method(#findMessages, [chatId]),
              returnValue: Future<List<_i4.LocalMessageEntity>>.value(
                  <_i4.LocalMessageEntity>[]))
          as _i3.Future<List<_i4.LocalMessageEntity>>);
  @override
  _i3.Future<void> deleteChat(String? chatId) =>
      (super.noSuchMethod(Invocation.method(#deleteChat, [chatId]),
          returnValue: Future<void>.value(),
          returnValueForMissingStub: Future<void>.value()) as _i3.Future<void>);
}
